(function registerQuizzes() {
  'use strict';

  const q = (prompt, options, answerIndex, explanation) => ({ prompt, options, answerIndex, explanation });

  const quizzes = [
    {
      id: 'foundation-core-1',
      area: 'foundations',
      kind: 'core',
      title: 'Core ML foundations diagnostic',
      questions: [
        q('A model has 99% training accuracy and 70% validation accuracy on a valid split. What is the first diagnosis?',
          ['High bias', 'High variance or train/validation mismatch', 'The learning rate is definitely too low', 'The labels must be wrong'], 1,
          'A large valid train/validation gap is evidence of variance or distribution mismatch. Verify split and leakage before selecting a regularizer.'),
        q('Why is cross-entropy usually preferred over accuracy as a training objective?',
          ['Accuracy is differentiable only for binary models', 'Cross-entropy supplies gradients that reflect confidence while accuracy is piecewise constant', 'Cross-entropy always produces calibrated probabilities', 'Accuracy cannot be computed on batches'], 1,
          'Accuracy changes only when the winning class changes, so it gives almost no local optimization signal. Cross-entropy differentiates through logits.'),
        q('What is the effect of increasing L2-style regularization too far?',
          ['It always lowers both bias and variance', 'It tends to increase variance', 'It can underfit by shrinking useful parameters', 'It has no effect when using Adam'], 2,
          'Stronger regularization can reduce variance but increases bias and can suppress task-relevant weights.'),
        q('A classifier score ranks examples correctly but predicted probabilities are overconfident. Which property is weak?',
          ['Discrimination', 'Calibration', 'Recall only', 'Specificity only'], 1,
          'Ranking can remain strong while predicted probability frequencies are wrong. Calibration measures probability reliability.'),
        q('What does an embedding dot product capture that cosine similarity removes?',
          ['Direction', 'Vector magnitude', 'Dimensionality', 'Orthogonality'], 1,
          'Cosine normalizes both vectors, while dot product is affected by their norms.'),
        q('Why can BatchNorm behave differently during inference?',
          ['It freezes the learned affine scale and shift', 'It uses stored running statistics instead of the current batch', 'It estimates statistics from each individual example', 'It recomputes statistics over the full training set for every request'], 1,
          'Training uses mini-batch statistics and updates running estimates. Evaluation uses the stored estimates while retaining learned affine parameters; it does not estimate moments per request or rescan training data.'),
        q('Which observation most strongly suggests a pipeline or optimization bug rather than overfitting?',
          ['Training loss falls while validation loss rises', 'A sufficiently expressive model cannot overfit ten examples', 'Performance drops only on an underrepresented slice', 'Both training and validation metrics plateau after training fits the tiny-batch check'], 1,
          'A sufficiently expressive model should memorize a tiny batch. Failure points to data, labels, forward/loss, gradients, optimizer, or capacity; a train/validation gap or slice failure is instead compatible with generalization problems.'),
        q('What does the chain rule enable in neural-network training?',
          ['Independent finite-difference estimates for every parameter', 'Efficient composition of local derivatives from loss to parameters', 'A guarantee that gradient descent reaches the global optimum', 'Elimination of vanishing gradients in deep compositions'], 1,
          'Backpropagation applies the chain rule through a computation graph and reuses upstream sensitivities. It neither requires per-parameter finite differences nor guarantees favorable optimization or gradient scale.'),
        q('Which split is safest for frames extracted from the same videos?',
          ['Random split by frame', 'Stratified split by frame', 'Group split by video', 'Chronological split by frame while allowing each video in both sets'], 2,
          'All frames from one video must stay together to avoid near-duplicate and contextual leakage. Random, stratified, or merely chronological frame-level splitting can still place correlated frames from one video on both sides.'),
        q('Why can a larger batch require learning-rate retuning?',
          ['It changes gradient-noise scale and the number of parameter updates', 'The expected gradient is identical, so the old learning rate is always optimal', 'The learning rate should always scale linearly with batch size for every optimizer', 'The learning rate should always scale inversely with batch size'], 0,
          'Global batch size changes gradient variance and optimizer steps per epoch. Linear scaling can be a starting heuristic in some regimes, but neither unchanged, universally linear, nor universally inverse scaling is guaranteed.'),
      ]
    },
    {
      id: 'task-loss-metric',
      area: 'foundations',
      kind: 'task-metric',
      title: 'Task → loss → metric decision drill',
      questions: [
        q('You classify one image into exactly one of 12 species. Which default output/loss pairing is correct?',
          ['12 independent sigmoids + BCE', '12 logits + softmax cross-entropy', '12 logits + MSE against a one-hot target', 'One scalar logit + binary cross-entropy'], 1,
          'Mutually exclusive classes form one categorical distribution, so use 12 logits with softmax cross-entropy. Independent BCE does not enforce competition, one-hot MSE is usually a poorer categorical objective, and one logit cannot represent 12 unordered classes.'),
        q('A photo may contain any subset of ten attributes. Which default pairing fits?',
          ['One softmax distribution over ten labels', 'One Bernoulli logit per label with BCE-with-logits', 'A multiclass margin loss that selects exactly one label', 'A regression head trained only on the number of present labels'], 1,
          'Use one Bernoulli logit per label; BCE-with-logits is the standard numerically stable factorized baseline. This modeling choice does not assert that labels are truly independent—correlations can be learned through shared features or richer structured models.'),
        q('Positive defects are 0.2% of inspection images. Which evaluation is most informative?',
          ['Overall accuracy at the default threshold', 'PR curve plus precision/recall at the operating threshold', 'ROC-AUC without checking the deployed operating point', 'F1 on a class-balanced resample with no prevalence correction'], 1,
          'PR behavior and the chosen operating point expose rare-positive retrieval under the real prevalence. Accuracy can be nearly perfect with no detections, ROC-AUC can obscure operational precision, and an artificially balanced evaluation changes precision.'),
        q('A segmentation system misses thin boundaries despite acceptable region IoU. What should you add?',
          ['More decimal places for mean IoU', 'Boundary F1 or a boundary-distance metric', 'Image-level ROC-AUC from the mean mask score', 'Pixel accuracy on masks downsampled further'], 1,
          'Region IoU can hide contour errors. Boundary F1 or a distance metric directly evaluates boundary quality; aggregate image scores, coarser masks, and extra precision on the same IoU do not expose the failure.'),
        q('A regression target has occasional extreme annotation errors. Which baseline loss is more robust than MSE?',
          ['Huber or MAE', 'MSE with greater weight on large residuals', 'MSE after squaring the target values', 'Cross-entropy over arbitrary value bins'], 0,
          'MSE squares large residuals. MAE or Huber reduces outlier influence; Huber retains smooth quadratic behavior near zero. Upweighting or transforming extremes worsens the mismatch, while arbitrary binning discards the regression geometry.'),
        q('For object detection, what does COCO-style mAP summarize?',
          ['AP at IoU 0.50 for one pooled category', 'Average precision across categories and multiple IoU thresholds', 'Average recall at one confidence threshold', 'The training localization loss averaged over matched boxes'], 1,
          'COCO mAP averages AP across categories and IoU thresholds. It is broader than AP50, and neither a single-threshold recall value nor an optimization loss.'),
        q('A hospital must catch at least 98% of a critical condition, with specialists reviewing positives. How should the threshold be selected?',
          ['Maximize accuracy', 'Meet the recall constraint, then maximize precision subject to review capacity and calibration', 'Always use 0.5', 'Maximize ROC-AUC'], 1,
          'The operational constraint fixes recall first. Precision, capacity, and calibrated risk then determine a useful threshold.'),
        q('Why might Dice loss be combined with pixelwise BCE for binary segmentation?',
          ['Dice calibrates each pixel while BCE measures only set overlap', 'BCE supplies dense local gradients while Dice aligns region overlap under imbalance', 'BCE is boundary-distance loss while Dice is a categorical classification loss', 'The combination makes the result independent of the decision threshold'], 1,
          'BCE supplies local probabilistic gradients and Dice emphasizes region overlap under imbalance. Their roles are not reversed, neither is a boundary-distance loss, and calibration and threshold selection still require measurement.'),
        q('A retrieval model should place a query image near a matching product and far from hard nonmatches. Which objective family fits?',
          ['Contrastive or triplet/ranking loss', 'Softmax cross-entropy over only the current catalog item IDs', 'MSE between matched embeddings with no negative or variance control', 'Image reconstruction loss on the query alone'], 0,
          'Metric-learning objectives explicitly shape relative embedding geometry with positives and negatives. Catalog-ID classification does not directly train unseen-item geometry, positive-only MSE can collapse, and reconstruction need not separate hard nonmatches.'),
        q('Two segmentation models have equal mean IoU. One misses small critical objects. What is the right next comparison?',
          ['Pixel accuracy aggregated over all images', 'Object-level recall sliced by size and class', 'Mean IoU rounded to more decimal places', 'Training-set Dice for the rare class'], 1,
          'Aggregate overlap can hide complete misses on small objects. Object-level and size/class-sliced recall exposes the failure; more aggregate precision or training-set metrics do not.'),
      ]
    },
    {
      id: 'rapid-fire-readiness',
      area: 'foundations',
      kind: 'rapid-fire',
      title: 'No-notes readiness rapid fire',
      questions: [
        q('Validation improves while training accuracy decreases after adding augmentation. Is that automatically bad?',
          ['Yes, training and validation accuracy must move in the same direction', 'No, harder augmented examples can reduce training accuracy while improving generalization', 'Yes, augmentation should be applied only after the model converges', 'No, because any validation improvement proves the split is valid'], 1,
          'Augmentation changes training difficulty, so lower training accuracy can accompany better valid-split generalization. The result is not automatically good either: split validity and slice behavior still need verification.'),
        q('What is the first thing to verify when production quality drops immediately after a deployment?',
          ['Retrain a higher-capacity model on the same data', 'Versioned code/model/threshold/preprocessing differences and input health', 'Increase regularization to improve generalization', 'Wait for a large labeled sample before checking serving changes'], 1,
          'An abrupt deployment-aligned change first implicates version, serving, preprocessing, threshold, traffic routing, or input-contract issues. Retraining and delayed labels come after checking the correlated operational change.'),
        q('Under the classical covariate-shift assumption, what changes?',
          ['P(Y|X) changes while P(X) is fixed', 'P(X) changes while P(Y|X) is assumed stable', 'P(Y) changes while P(X|Y) is assumed stable', 'Only the model prediction distribution changes'], 1,
          'Classical covariate shift changes the input distribution P(X) while assuming the conditional P(Y|X) remains stable. A conditional change is concept drift; a changed class prior under stable P(X|Y) is label shift; prediction shift alone does not identify the cause.'),
        q('Why does AdamW decouple weight decay?',
          ['An L2 gradient penalty and direct decay are identical under every optimizer', 'Adaptive gradient scaling makes an L2 penalty differ from direct parameter shrinkage', 'Decoupling removes the need for first- and second-moment estimates', 'Decoupling automatically chooses which parameter groups should decay'], 1,
          'Adam scales gradient coordinates adaptively, so adding λθ to the gradient is not the same as direct shrinkage. AdamW separates the decay update; moment estimation and explicit parameter-group choices still remain.'),
        q('Which monitoring signal is the strongest evidence of concept drift?',
          ['The input feature mean changed', 'Prediction entropy changed', 'Labeled conditional performance changed under comparable evaluation', 'An embedding-distance alarm fired on unlabeled traffic'], 2,
          'Concept drift concerns P(Y|X). Input, embedding, or prediction shifts are useful alarms but do not identify that conditional change; comparable labeled outcomes provide the strongest evidence among these choices.'),
        q('Why can nearest-neighbor retrieval require a full index rebuild after encoder replacement?',
          ['Matching embedding dimensions guarantees old and new vectors remain comparable', 'Old and new embeddings may occupy incompatible vector spaces', 'L2-normalizing both versions always aligns their coordinate systems', 'A dual-index migration changes only storage cost, not result semantics'], 1,
          'Vectors from different representation versions are generally not comparable even when dimension and normalization match. Re-embedding the catalog—or deliberately running version-compatible dual indexes—is needed to preserve query/index semantics.'),
        q('What is a strong baseline for a new CV problem with limited data?',
          ['Train the largest available architecture from random initialization', 'A simple pretrained model with a clear metric and valid split', 'Select the newest architecture by repeatedly tuning on the test set', 'Freeze a pretrained backbone permanently without comparing fine-tuning'], 1,
          'A simple pretrained baseline quickly tests data, labels, metric, and transfer. Scratch training, test-set selection, and an unvalidated always-frozen policy confound the comparison.'),
        q('What does a canary deployment add beyond shadowing?',
          ['Offline replay of historical requests', 'Real user decisions and impact on a controlled fraction', 'Mirrored live traffic whose outputs are never served', 'A full rollout protected only by the ability to roll back'], 1,
          'A canary serves a limited share of real decisions, exposing actual user and system impact while containing risk. Offline replay and non-serving mirrored traffic are not canaries, while a full rollout is not controlled exposure.'),
        q('Why should threshold and model version be tracked separately?',
          ['Embedding the threshold in a model filename fully identifies every serving decision', 'Operational behavior can change without retraining when the threshold changes', 'Threshold versioning matters only when the encoder architecture changes', 'Logged score histograms are enough to reconstruct the exact threshold later'], 1,
          'A threshold is independent production configuration that can change precision, recall, load, and risk without new weights. Filenames or score histograms do not substitute for recording the exact deployed value and rollout.'),
        q('When is a random validation split especially dangerous?',
          ['Independent tabular rows sampled from the deployment distribution', 'Temporal prediction or grouped entities with correlated samples', 'A small independent dataset that uses stratification', 'Independent images with no shared subject, site, or acquisition session'], 1,
          'Random splitting leaks future or group-specific information when deployment requires generalization across time or entities. Small size may increase uncertainty, but without dependence it does not create this particular leakage.'),
      ]
    },
    {
      id: 'modern-cv-judgment',
      area: 'modern-cv',
      kind: 'modern-cv',
      title: 'Modern CV model-selection check',
      questions: [
        q('You need cross-modal text-to-image retrieval across a broad catalog. Best starting representation?',
          ['A supervised image classifier’s final class logits', 'CLIP-style dual image/text encoders in a shared embedding space', 'A self-supervised image encoder with no text objective', 'An object detector’s box-regression features without language training'], 1,
          'CLIP-style dual encoders explicitly align image and text embeddings in a shared space, making them a strong retrieval baseline. Image-only supervision may produce useful visual features but does not provide the required cross-modal alignment.'),
        q('You need reusable visual features for dense tasks but text alignment is not important. Best starting point?',
          ['DINOv2-style self-supervised features', 'CLIP text embeddings used without an image encoder', 'A classifier’s final class probabilities as the dense feature map', 'Raw RGB patches compared directly with cosine similarity'], 0,
          'DINOv2 targets reusable visual representations and often transfers to dense perception with task heads. Text-only, class-probability, and raw-pixel representations do not provide comparable spatial visual features.'),
        q('What is the main computational risk of reducing ViT patch size at fixed resolution?',
          ['Token count falls because each patch has fewer pixels', 'More tokens and much higher attention cost', 'Attention cost stays linear because embedding width is unchanged', 'Only the patch projection cost changes; transformer-block cost is fixed'], 1,
          'Smaller patches increase token count. Full self-attention grows quadratically in token count, so fixed embedding width does not make transformer-block cost linear or constant.'),
        q('What does canonical DETR replace with set prediction and matching?',
          ['All image preprocessing', 'Anchor design and standard NMS in the core detector', 'The classification loss', 'The image backbone'], 1,
          'Object queries and bipartite matching produce a set of distinct predictions, removing anchors and canonical NMS.'),
        q('What is a sensible production role for SAM2 in a domain with limited labels?',
          ['Use its masks as ground truth without a domain audit', 'Annotation acceleration and an evaluated promptable component', 'Replace a validated domain model because prompts eliminate distribution shift', 'Feed its masks downstream without measuring propagated errors'], 1,
          'SAM2 can accelerate annotation and support interactive segmentation, but domain performance and workflow safety require evaluation. Promptability does not remove distribution shift, label review, or downstream error analysis.'),
        q('Grounding DINO plus SAM composes which two capabilities?',
          ['Text-conditioned boxes followed by promptable masks', 'Promptable masks followed by text-conditioned box training', 'Closed-set class logits followed by mask upsampling', 'Class-agnostic boxes followed by an ungrounded captioner'], 0,
          'Grounding DINO maps phrases to boxes, and those boxes can prompt SAM to produce masks. The composition is open-vocabulary grounding followed by promptable segmentation, not closed-set classification or caption generation.'),
        q('Why can a VLM be dangerous for structured document extraction?',
          ['Schema-valid output guarantees every field is visually supported', 'Fluent output can invent unsupported fields unless grounded and validated', 'Removing OCR always improves evidence fidelity', 'Low decoding temperature guarantees factual extraction'], 1,
          'Generative fluency can hide unsupported fields. Schema validity, OCR-free generation, or low temperature does not prove visual grounding; use evidence links, validation, abstention, and field-level evaluation.'),
        q('When might a compact CNN beat a transformer in production?',
          ['Whenever the transformer has a higher pretraining benchmark, regardless of hardware', 'Tight edge latency, small data, mature optimized kernels, and local patterns', 'Whenever input resolution is fixed, regardless of target runtime', 'Whenever the training set is small, even if a strong transformer checkpoint transfers better'], 1,
          'Architecture choice includes data, transfer quality, and target hardware. CNN inductive bias and optimized kernels can dominate under the stated constraints, but neither fixed resolution nor dataset size alone decides the result.'),
        q('What must be measured after INT8 quantization?',
          ['Calibration-set accuracy before conversion only', 'End-to-end target-hardware latency plus overall and slice accuracy', 'Kernel microbenchmark speed without preprocessing or transfer overhead', 'Aggregate accuracy without latency or slice checks'], 1,
          'Quantization value depends on actual target-runtime support and acceptable end-to-end quality. Calibration data, kernel speed, or aggregate accuracy alone can miss conversion, overhead, fallback, and slice regressions.'),
        q('Synthetic diffusion data improves training accuracy. What validates its usefulness?',
          ['A blinded realism rating of generated samples alone', 'Improvement on a real, untouched, deployment-representative holdout without slice regressions', 'A monotonic gain as more synthetic samples are added', 'Lower diffusion-model loss on its own training distribution'], 1,
          'Only untouched real-data evaluation demonstrates useful transfer. Realism ratings, synthetic volume, and generator loss do not rule out artifacts, leakage, label errors, or deployment-slice regressions.')
      ]
    }
  ];

  window.InterviewPrepData = {
    ...(window.InterviewPrepData || {}),
    quizzes
  };
})();
