(function registerQuizzes() {
  'use strict';

  const q = (prompt, options, answerIndex, explanation) => ({ prompt, options, answerIndex, explanation });

  const quizzes = [
    {
      id: 'foundation-core-1',
      area: 'foundations',
      kind: 'core',
      title: 'Core ML foundations diagnostic',
      questions: [
        q('A model has 99% training accuracy and 70% validation accuracy on a valid split. What is the first diagnosis?',
          ['High bias', 'High variance or train/validation mismatch', 'The learning rate is definitely too low', 'The labels must be wrong'], 1,
          'A large valid train/validation gap is evidence of variance or distribution mismatch. Verify split and leakage before selecting a regularizer.'),
        q('Why is cross-entropy usually preferred over accuracy as a training objective?',
          ['Accuracy is differentiable only for binary models', 'Cross-entropy supplies gradients that reflect confidence while accuracy is piecewise constant', 'Cross-entropy always produces calibrated probabilities', 'Accuracy cannot be computed on batches'], 1,
          'Accuracy changes only when the winning class changes, so it gives almost no local optimization signal. Cross-entropy differentiates through logits.'),
        q('What is the effect of increasing L2-style regularization too far?',
          ['It always lowers both bias and variance', 'It tends to increase variance', 'It can underfit by shrinking useful parameters', 'It has no effect when using Adam'], 2,
          'Stronger regularization can reduce variance but increases bias and can suppress task-relevant weights.'),
        q('A classifier score ranks examples correctly but predicted probabilities are overconfident. Which property is weak?',
          ['Discrimination', 'Calibration', 'Recall only', 'Specificity only'], 1,
          'Ranking can remain strong while predicted probability frequencies are wrong. Calibration measures probability reliability.'),
        q('What does an embedding dot product capture that cosine similarity removes?',
          ['Direction', 'Vector magnitude', 'Dimensionality', 'Orthogonality'], 1,
          'Cosine normalizes both vectors, while dot product is affected by their norms.'),
        q('Why can BatchNorm behave differently during inference?',
          ['It removes nonlinearities', 'It uses stored running statistics instead of the current batch', 'It disables learned scale and shift', 'It converts weights to integers'], 1,
          'Training computes batch statistics and updates running estimates. Inference uses frozen running statistics in evaluation mode.'),
        q('Which observation most strongly suggests a pipeline or optimization bug rather than overfitting?',
          ['Validation is worse than training', 'A large model cannot overfit ten examples', 'Performance drops on one rare slice', 'Training takes longer than expected'], 1,
          'A sufficiently expressive model should memorize a tiny batch. Failure points to data, labels, forward/loss, gradients, optimizer, or capacity.'),
        q('What does the chain rule enable in neural-network training?',
          ['Exact global optimization', 'Efficient composition of local derivatives from loss to parameters', 'Removal of all non-convexity', 'Automatic calibration'], 1,
          'Backpropagation applies the chain rule through a computation graph, reusing upstream sensitivities.'),
        q('Which split is safest for frames extracted from the same videos?',
          ['Random split by frame', 'Stratified split by frame', 'Group split by video', 'Sort by frame brightness'], 2,
          'All frames from one video must stay together to avoid near-duplicate and contextual leakage.'),
        q('Why can a larger batch require learning-rate retuning?',
          ['It changes gradient-noise scale and the number of parameter updates', 'It changes the number of model parameters', 'It makes the loss non-differentiable', 'It disables momentum'], 0,
          'Global batch size changes gradient variance, optimizer steps per epoch, and hardware behavior; schedules and regularization may need adjustment.')
      ]
    },
    {
      id: 'task-loss-metric',
      area: 'foundations',
      kind: 'task-metric',
      title: 'Task → loss → metric decision drill',
      questions: [
        q('You classify one image into exactly one of 12 species. Which default output/loss pairing is correct?',
          ['12 independent sigmoids + BCE', '12 logits + softmax cross-entropy', 'One scalar + MSE', '12 masks + Dice'], 1,
          'Mutually exclusive classes form one categorical distribution, so use logits with softmax cross-entropy.'),
        q('A photo may contain any subset of ten attributes. Which default pairing fits?',
          ['Softmax CE', 'Independent logits with BCE-with-logits', 'Huber loss', 'Triplet loss only'], 1,
          'Multilabel targets are independent binary outputs; BCE-with-logits is the stable standard baseline.'),
        q('Positive defects are 0.2% of inspection images. Which evaluation is most informative?',
          ['Accuracy alone', 'PR curve plus precision/recall at the operating threshold', 'Training loss alone', 'R²'], 1,
          'PR behavior and the chosen operating point expose whether rare-positive retrieval is useful. Accuracy can be nearly perfect with no detections.'),
        q('A segmentation system misses thin boundaries despite acceptable region IoU. What should you add?',
          ['Only pixel accuracy', 'Boundary F1 or a boundary-distance metric', 'ROC-AUC across images only', 'R²'], 1,
          'Region overlap can hide edge errors. Boundary-aware metrics directly evaluate contour quality.'),
        q('A regression target has occasional extreme annotation errors. Which baseline loss is more robust than MSE?',
          ['Huber or MAE', 'Categorical cross-entropy', 'Dice', 'Focal loss'], 0,
          'MSE squares large residuals. MAE or Huber reduces outlier influence; Huber retains smooth quadratic behavior near zero.'),
        q('For object detection, what does COCO-style mAP summarize?',
          ['Only classification accuracy', 'Average precision across categories and multiple IoU thresholds', 'Mean pixel accuracy', 'Calibration at one confidence threshold'], 1,
          'COCO mAP averages AP across classes and IoU thresholds, rewarding both classification and localization quality.'),
        q('A hospital must catch at least 98% of a critical condition, with specialists reviewing positives. How should the threshold be selected?',
          ['Maximize accuracy', 'Meet the recall constraint, then maximize precision subject to review capacity and calibration', 'Always use 0.5', 'Maximize ROC-AUC'], 1,
          'The operational constraint fixes recall first. Precision, capacity, and calibrated risk then determine a useful threshold.'),
        q('Why might Dice loss be combined with pixelwise BCE for binary segmentation?',
          ['Dice makes labels continuous', 'BCE supplies dense local gradients while Dice aligns region overlap under imbalance', 'BCE measures boundary distance', 'The combination guarantees calibration'], 1,
          'The two losses provide complementary optimization signals. Calibration still requires measurement.'),
        q('A retrieval model should place a query image near a matching product and far from hard nonmatches. Which objective family fits?',
          ['Contrastive or triplet/ranking loss', 'Pixelwise BCE', 'Only MSE on class IDs', 'CTC loss'], 0,
          'Metric-learning objectives explicitly shape relative embedding geometry using positives and negatives.'),
        q('Two segmentation models have equal mean IoU. One misses small critical objects. What is the right next comparison?',
          ['Keep only mean IoU', 'Object-level recall sliced by size and class', 'Training throughput only', 'Number of parameters only'], 1,
          'Aggregate overlap can hide complete misses on small objects. Object-level and size-sliced metrics reveal the safety-relevant difference.')
      ]
    },
    {
      id: 'rapid-fire-readiness',
      area: 'foundations',
      kind: 'rapid-fire',
      title: 'No-notes readiness rapid fire',
      questions: [
        q('Validation improves while training accuracy decreases after adding augmentation. Is that automatically bad?',
          ['Yes, training accuracy must always rise', 'No, harder augmented examples can reduce training accuracy while improving generalization', 'Yes, augmentation only belongs in validation', 'No, because validation is always unbiased'], 1,
          'Augmentation changes the training distribution and difficulty. The result can be desirable if validation and slice behavior improve on a valid split.'),
        q('What is the first thing to verify when production quality drops immediately after a deployment?',
          ['Retrain a larger model', 'Versioned code/model/threshold/preprocessing differences and input health', 'Increase dropout', 'Collect six months of labels'], 1,
          'An abrupt deployment-aligned change strongly suggests version, serving, preprocessing, threshold, or traffic-routing issues.'),
        q('Covariate drift means:',
          ['P(Y|X) changes only', 'P(X) changes', 'The model file is corrupted', 'The class count must increase'], 1,
          'Covariate drift is a change in the input distribution P(X). It may or may not reduce model quality.'),
        q('Why does AdamW decouple weight decay?',
          ['To prevent gradients', 'Adaptive gradient scaling makes an L2 penalty differ from direct parameter shrinkage', 'To remove momentum', 'To make training deterministic'], 1,
          'Under adaptive optimizers, adding λθ to the gradient is scaled per parameter. AdamW applies shrinkage separately.'),
        q('Which monitoring signal proves concept drift?',
          ['Input mean changed', 'Prediction entropy changed', 'Labeled conditional performance changed under comparable evaluation', 'GPU utilization changed'], 2,
          'Concept drift concerns P(Y|X). Input or prediction shifts are indicators, not proof; comparable labeled outcomes are stronger evidence.'),
        q('Why can nearest-neighbor retrieval require a full index rebuild after encoder replacement?',
          ['URLs change', 'Old and new embeddings may occupy incompatible vector spaces', 'ANN cannot store floats', 'Cosine similarity becomes nondifferentiable'], 1,
          'Vectors from different representation versions are generally not comparable, so query and catalog embeddings must be version compatible.'),
        q('What is a strong baseline for a new CV problem with limited data?',
          ['Train the largest model from scratch', 'A simple pretrained model with a clear metric and valid split', 'Skip labeling and rely on prompts', 'Optimize only latency'], 1,
          'A pretrained baseline quickly tests data, labels, metric, and transfer before costly architecture work.'),
        q('What does a canary deployment add beyond shadowing?',
          ['No traffic', 'Real user decisions and impact on a controlled fraction', 'Perfect offline labels', 'Zero operational risk'], 1,
          'A canary affects a limited share of real decisions, measuring actual impact while containing risk. Shadowing does not affect outcomes.'),
        q('Why should threshold and model version be tracked separately?',
          ['Thresholds never change', 'Operational behavior can change without retraining when the threshold changes', 'Models do not output scores', 'Only thresholds need rollback'], 1,
          'Decision thresholds are independent production configuration and can materially change precision, recall, load, and risk.'),
        q('When is a random validation split especially dangerous?',
          ['IID tabular rows with no entities', 'Temporal prediction or grouped entities with correlated samples', 'A balanced synthetic dataset only', 'When using a linear model'], 1,
          'Random splitting leaks future or group-specific information when deployment requires generalization across time or entities.')
      ]
    },
    {
      id: 'modern-cv-judgment',
      area: 'modern-cv',
      kind: 'modern-cv',
      title: 'Modern CV model-selection check',
      questions: [
        q('You need cross-modal text-to-image retrieval across a broad catalog. Best starting representation?',
          ['A randomly initialized CNN', 'A CLIP-style joint image-text encoder', 'Only a segmentation mask decoder', 'A scalar regression head'], 1,
          'CLIP-style models explicitly align image and text embeddings, making them a strong retrieval baseline.'),
        q('You need reusable visual features for dense tasks but text alignment is not important. Best starting point?',
          ['DINOv2-style self-supervised features', 'Only a language model', 'Focal loss without an encoder', 'One-hot file names'], 0,
          'DINOv2 targets general visual representations and often transfers to dense perception with task heads.'),
        q('What is the main computational risk of reducing ViT patch size at fixed resolution?',
          ['Fewer tokens', 'More tokens and much higher attention cost', 'No positional information is needed', 'The model becomes a CNN'], 1,
          'Smaller patches increase token count. Full attention cost grows quadratically with the number of tokens.'),
        q('What does canonical DETR replace with set prediction and matching?',
          ['All image preprocessing', 'Anchor design and standard NMS in the core detector', 'The classification loss', 'The image backbone'], 1,
          'Object queries and bipartite matching produce a set of distinct predictions, removing anchors and canonical NMS.'),
        q('What is a sensible production role for SAM2 in a domain with limited labels?',
          ['Assume perfect automated diagnosis', 'Annotation acceleration and an evaluated promptable component', 'Replace all metrics', 'Generate text labels without review'], 1,
          'SAM2 can reduce annotation effort and support interactive segmentation, but domain performance and workflow safety still require evaluation.'),
        q('Grounding DINO plus SAM composes which two capabilities?',
          ['Text-conditioned boxes followed by promptable masks', 'Depth estimation followed by OCR', 'Classification followed by regression', 'Compression followed by distillation'], 0,
          'Grounding DINO maps phrases to boxes; boxes can prompt SAM to create masks.'),
        q('Why can a VLM be dangerous for structured document extraction?',
          ['It cannot process images', 'Fluent output can invent unsupported fields unless grounded and validated', 'It never uses tokens', 'It always runs on edge devices'], 1,
          'Generative fluency can hide hallucination. Schema checks, evidence grounding, abstention, and field-level evaluation are required.'),
        q('When might a compact CNN beat a transformer in production?',
          ['Never', 'Tight edge latency, small data, mature optimized kernels, and local patterns', 'Only when classes are balanced', 'Only for text'], 1,
          'Architecture choice must include data and target hardware. CNN inductive bias and optimized deployment can dominate.'),
        q('What must be measured after INT8 quantization?',
          ['Only model file size', 'End-to-end target-hardware latency plus overall and slice accuracy', 'Only training loss', 'Only FLOPs'], 1,
          'Quantization value depends on real runtime support and acceptable quality across sensitive slices.'),
        q('Synthetic diffusion data improves training accuracy. What validates its usefulness?',
          ['Visual realism alone', 'Improvement on a real, untouched, deployment-representative holdout without slice regressions', 'More synthetic samples', 'Lower generator loss'], 1,
          'Only real-data evaluation demonstrates transfer. Synthetic artifacts and label assumptions can create shortcuts.')
      ]
    }
  ];

  window.InterviewPrepData = {
    ...(window.InterviewPrepData || {}),
    quizzes
  };
})();
