(function registerQuizzes() {
  'use strict';

  const q = (prompt, options, answerIndex, explanation) => ({ prompt, options, answerIndex, explanation });

  const quizzes = [
    {
      id: 'foundation-core-1',
      area: 'foundations',
      kind: 'core',
      title: 'Core ML foundations diagnostic',
      questions: [
        q('A model has 99% training accuracy and 70% validation accuracy on a valid split. What is the first diagnosis?',
          ['High bias', 'High variance or train/validation mismatch', 'The learning rate is definitely too low', 'The labels must be wrong'], 1,
          'A large valid train/validation gap is evidence of variance or distribution mismatch. Verify split and leakage before selecting a regularizer.'),
        q('Why is cross-entropy usually preferred over accuracy as a training objective?',
          ['Accuracy is differentiable only for binary models', 'Cross-entropy supplies gradients that reflect confidence while accuracy is piecewise constant', 'Cross-entropy always produces calibrated probabilities', 'Accuracy cannot be computed on batches'], 1,
          'Accuracy changes only when the winning class changes, so it gives almost no local optimization signal. Cross-entropy differentiates through logits.'),
        q('What is the effect of increasing L2-style regularization too far?',
          ['It always lowers both bias and variance', 'It tends to increase variance', 'It can underfit by shrinking useful parameters', 'It has no effect when using Adam'], 2,
          'Stronger regularization can reduce variance but increases bias and can suppress task-relevant weights.'),
        q('A classifier score ranks examples correctly but predicted probabilities are overconfident. Which property is weak?',
          ['Discrimination', 'Calibration', 'Recall only', 'Specificity only'], 1,
          'Ranking can remain strong while predicted probability frequencies are wrong. Calibration measures probability reliability.'),
        q('What does an embedding dot product capture that cosine similarity removes?',
          ['Direction', 'Vector magnitude', 'Dimensionality', 'Orthogonality'], 1,
          'Cosine normalizes both vectors, while dot product is affected by their norms.'),
        q('Why can BatchNorm behave differently during inference?',
          ['It freezes the learned affine scale and shift', 'It uses stored running statistics instead of the current batch', 'It estimates statistics from each individual example', 'It recomputes statistics over the full training set for every request'], 1,
          'Training uses mini-batch statistics and updates running estimates. Evaluation uses the stored estimates while retaining learned affine parameters; it does not estimate moments per request or rescan training data.'),
        q('Which observation most strongly suggests a pipeline or optimization bug rather than overfitting?',
          ['Training loss falls while validation loss rises', 'A sufficiently expressive model cannot overfit ten examples', 'Performance drops only on an underrepresented slice', 'Both training and validation metrics plateau after training fits the tiny-batch check'], 1,
          'A sufficiently expressive model should memorize a tiny batch. Failure points to data, labels, forward/loss, gradients, optimizer, or capacity; a train/validation gap or slice failure is instead compatible with generalization problems.'),
        q('What does the chain rule enable in neural-network training?',
          ['Independent finite-difference estimates for every parameter', 'Efficient composition of local derivatives from loss to parameters', 'A guarantee that gradient descent reaches the global optimum', 'Elimination of vanishing gradients in deep compositions'], 1,
          'Backpropagation applies the chain rule through a computation graph and reuses upstream sensitivities. It neither requires per-parameter finite differences nor guarantees favorable optimization or gradient scale.'),
        q('Which split is safest for frames extracted from the same videos?',
          ['Random split by frame', 'Stratified split by frame', 'Group split by video', 'Chronological split by frame while allowing each video in both sets'], 2,
          'All frames from one video must stay together to avoid near-duplicate and contextual leakage. Random, stratified, or merely chronological frame-level splitting can still place correlated frames from one video on both sides.'),
        q('Why can a larger batch require learning-rate retuning?',
          ['It changes gradient-noise scale and the number of parameter updates', 'The expected gradient is identical, so the old learning rate is always optimal', 'The learning rate should always scale linearly with batch size for every optimizer', 'The learning rate should always scale inversely with batch size'], 0,
          'Global batch size changes gradient variance and optimizer steps per epoch. Linear scaling can be a starting heuristic in some regimes, but neither unchanged, universally linear, nor universally inverse scaling is guaranteed.'),
      ]
    },
    {
      id: 'task-loss-metric',
      area: 'foundations',
      kind: 'task-metric',
      title: 'Task → loss → metric decision drill',
      questions: [
        q('You classify one image into exactly one of 12 species. Which default output/loss pairing is correct?',
          ['12 independent sigmoids + BCE', '12 logits + softmax cross-entropy', '12 logits + MSE against a one-hot target', 'One scalar logit + binary cross-entropy'], 1,
          'Mutually exclusive classes form one categorical distribution, so use 12 logits with softmax cross-entropy. Independent BCE does not enforce competition, one-hot MSE is usually a poorer categorical objective, and one logit cannot represent 12 unordered classes.'),
        q('A photo may contain any subset of ten attributes. Which default pairing fits?',
          ['One softmax distribution over ten labels', 'One Bernoulli logit per label with BCE-with-logits', 'A multiclass margin loss that selects exactly one label', 'A regression head trained only on the number of present labels'], 1,
          'Use one Bernoulli logit per label; BCE-with-logits is the standard numerically stable factorized baseline. This modeling choice does not assert that labels are truly independent—correlations can be learned through shared features or richer structured models.'),
        q('Positive defects are 0.2% of inspection images. Which evaluation is most informative?',
          ['Overall accuracy at the default threshold', 'PR curve plus precision/recall at the operating threshold', 'ROC-AUC without checking the deployed operating point', 'F1 on a class-balanced resample with no prevalence correction'], 1,
          'PR behavior and the chosen operating point expose rare-positive retrieval under the real prevalence. Accuracy can be nearly perfect with no detections, ROC-AUC can obscure operational precision, and an artificially balanced evaluation changes precision.'),
        q('A segmentation system misses thin boundaries despite acceptable region IoU. What should you add?',
          ['More decimal places for mean IoU', 'Boundary F1 or a boundary-distance metric', 'Image-level ROC-AUC from the mean mask score', 'Pixel accuracy on masks downsampled further'], 1,
          'Region IoU can hide contour errors. Boundary F1 or a distance metric directly evaluates boundary quality; aggregate image scores, coarser masks, and extra precision on the same IoU do not expose the failure.'),
        q('A regression target has occasional extreme annotation errors. Which baseline loss is more robust than MSE?',
          ['Huber or MAE', 'MSE with greater weight on large residuals', 'MSE after squaring the target values', 'Cross-entropy over arbitrary value bins'], 0,
          'MSE squares large residuals. MAE or Huber reduces outlier influence; Huber retains smooth quadratic behavior near zero. Upweighting or transforming extremes worsens the mismatch, while arbitrary binning discards the regression geometry.'),
        q('For object detection, what does COCO-style mAP summarize?',
          ['AP at IoU 0.50 for one pooled category', 'Average precision across categories and multiple IoU thresholds', 'Average recall at one confidence threshold', 'The training localization loss averaged over matched boxes'], 1,
          'COCO mAP averages AP across categories and IoU thresholds. It is broader than AP50, and neither a single-threshold recall value nor an optimization loss.'),
        q('A hospital must catch at least 98% of a critical condition, with specialists reviewing positives. How should the threshold be selected?',
          ['Maximize accuracy', 'Meet the recall constraint, then maximize precision subject to review capacity and calibration', 'Always use 0.5', 'Maximize ROC-AUC'], 1,
          'The operational constraint fixes recall first. Precision, capacity, and calibrated risk then determine a useful threshold.'),
        q('Why might Dice loss be combined with pixelwise BCE for binary segmentation?',
          ['Dice calibrates each pixel while BCE measures only set overlap', 'BCE supplies dense local gradients while Dice aligns region overlap under imbalance', 'BCE is boundary-distance loss while Dice is a categorical classification loss', 'The combination makes the result independent of the decision threshold'], 1,
          'BCE supplies local probabilistic gradients and Dice emphasizes region overlap under imbalance. Their roles are not reversed, neither is a boundary-distance loss, and calibration and threshold selection still require measurement.'),
        q('A retrieval model should place a query image near a matching product and far from hard nonmatches. Which objective family fits?',
          ['Contrastive or triplet/ranking loss', 'Softmax cross-entropy over only the current catalog item IDs', 'MSE between matched embeddings with no negative or variance control', 'Image reconstruction loss on the query alone'], 0,
          'Metric-learning objectives explicitly shape relative embedding geometry with positives and negatives. Catalog-ID classification does not directly train unseen-item geometry, positive-only MSE can collapse, and reconstruction need not separate hard nonmatches.'),
        q('Two segmentation models have equal mean IoU. One misses small critical objects. What is the right next comparison?',
          ['Pixel accuracy aggregated over all images', 'Object-level recall sliced by size and class', 'Mean IoU rounded to more decimal places', 'Training-set Dice for the rare class'], 1,
          'Aggregate overlap can hide complete misses on small objects. Object-level and size/class-sliced recall exposes the failure; more aggregate precision or training-set metrics do not.'),
      ]
    },
    {
      id: 'linear-algebra-basics',
      area: 'foundations',
      kind: 'linear-algebra',
      title: 'Linear algebra for ML and CV',
      questions: [
        q('A batch of 32 feature vectors has shape [32, 128], and a linear layer weight has shape [128, 10]. What is the output shape?',
          ['[128, 10]', '[10, 32]', '[32, 10]', '[32, 128]'], 2,
          'Matrix multiplication contracts the shared 128-dimensional feature axis. Each of the 32 rows is mapped to ten output coordinates, producing [32, 10].'),
        q('Two nonzero embeddings have cosine similarity 1. What can you conclude?',
          ['They are identical element by element', 'They point in the same direction but may have different magnitudes', 'They are orthogonal', 'Their dot product must equal 1'], 1,
          'Cosine similarity normalizes both norms, so a value of 1 means the vectors are positive scalar multiples. Their magnitudes and unnormalized dot product can differ.'),
        q('A matrix has five columns, but one column is an exact linear combination of the other four. What follows?',
          ['Its column rank is exactly five', 'Its rows must all be orthogonal', 'Its column rank is at most four', 'It must have five nonzero singular values'], 2,
          'The dependent column adds no new basis direction, so the column space has dimension at most four. Consequently there can be at most four nonzero singular values.'),
        q('For a unit vector u, which expression projects a vector x onto the line spanned by u?',
          ['x(uᵀu)', 'u(uᵀx)', 'x - u(uᵀx)', 'u + x'], 1,
          'The scalar uᵀx is the signed coordinate of x along unit direction u, and multiplying by u maps that coordinate back into the original space. The final option is the orthogonal residual.'),
        q('Why are eigenvectors of a centered data covariance matrix useful for PCA?',
          ['They are always the original coordinate axes', 'They guarantee the original features are independent', 'They minimize every supervised prediction loss', 'They give directions of variance, ordered by their eigenvalues'], 3,
          'A covariance matrix is symmetric, and its orthonormal eigenvectors define directions whose variances are the corresponding eigenvalues. PCA keeps the leading directions; it does not guarantee statistical independence or supervised optimality.'),
        q('For a rectangular matrix A = UΣVᵀ, what is the best rank-k approximation under Frobenius norm?',
          ['Keep the k smallest singular values', 'Keep the first k original columns regardless of basis', 'Keep the k largest singular values and their singular vectors', 'Replace every singular value with their mean'], 2,
          'The truncated SVD retaining the k largest singular triplets is the optimal rank-k approximation in Frobenius and spectral norm. Original column order does not generally identify the informative subspace.'),
        q('How should PCA be used in a train/validation pipeline to avoid leakage?',
          ['Fit PCA separately on validation data for the cleanest estimate', 'Fit centering and principal directions on training data, then transform validation data with those fitted values', 'Fit PCA once on the combined train and validation features', 'Choose the number of components by maximizing test-set accuracy'], 1,
          'Centering statistics and principal directions are learned parameters. Fit them only on the training partition, tune component count without the test set, and reuse the fitted transform on held-out data.'),
        q('All catalog and query embeddings are L2-normalized. Which ranking relationship then holds?',
          ['Dot product still depends on vector magnitude', 'Cosine and Euclidean rankings must be unrelated', 'Every pair has the same dot product', 'Higher dot product means higher cosine similarity and smaller squared Euclidean distance'], 3,
          'For unit vectors, dot product equals cosine similarity and squared distance is 2 − 2·dot. Maximizing dot or cosine is therefore equivalent to minimizing Euclidean distance, up to ties.'),
      ]
    },
    {
      id: 'statistics-inference',
      area: 'foundations',
      kind: 'statistics',
      title: 'Statistical inference and validation',
      questions: [
        q('Before choosing an estimator for an online experiment, what should be specified first?',
          ['The smallest p-value the dashboard can display', 'The model architecture used by the product', 'The estimand: population, treatment contrast, outcome, and time horizon', 'The bootstrap random seed'], 2,
          'An estimand states the quantity the study intends to learn. Estimator, uncertainty method, and data collection should follow from that target rather than silently redefining it.'),
        q('A frequentist 95% confidence interval is computed correctly. Which interpretation is valid?',
          ['There is a 95% probability that this fixed parameter lies in this realized interval', 'Across repeated samples, the interval procedure covers the fixed parameter about 95% of the time', 'Ninety-five percent of observed outcomes lie inside the interval', 'The null hypothesis has a 5% probability of being true'], 1,
          'Frequentist coverage describes the long-run behavior of the interval-producing procedure. After observing one interval, the fixed parameter is not assigned a frequentist probability by that calculation.'),
        q('What does a p-value of 0.03 mean in a pre-specified hypothesis test?',
          ['The null hypothesis is false with probability 0.97', 'The alternative hypothesis is true with probability 0.97', 'The effect has a 3% chance of being practically important', 'If the null and test assumptions hold, results at least this extreme occur with probability 0.03'], 3,
          'A p-value is a tail probability under the null model and analysis assumptions. It is not a posterior probability for either hypothesis and does not measure practical importance.'),
        q('With effect size and significance threshold fixed, which change generally increases statistical power?',
          ['Add more unplanned outcome metrics', 'Stop whenever the running p-value first crosses the threshold', 'Increase sample size or reduce outcome variance', 'Use a noisier measurement process'], 2,
          'More independent information or lower variance makes the sampling distributions easier to distinguish. Uncorrected metric multiplicity and optional stopping inflate false positives rather than supplying valid power.'),
        q('A patient contributes many correlated images, and deployment is to unseen patients. Which validation split matches that estimand?',
          ['Randomly split individual images while preserving class balance', 'Group all images from each patient into a single partition', 'Duplicate rare-patient images across train and validation', 'Tune on the test patients until every subgroup improves'], 1,
          'Patient-level grouping prevents near-duplicate anatomy and acquisition context from leaking across partitions. The held-out unit must match the unseen-patient deployment claim.'),
        q('You bootstrap an error rate from data containing multiple frames per video. What is the defensible resampling unit?',
          ['Resample frames independently and ignore video identity', 'Resample only misclassified frames', 'Resample videos, retaining their within-video frames', 'Resample model parameters instead of observations'], 2,
          'The bootstrap should preserve the dependence structure of the sampling process. Resampling whole videos treats videos as independent units; frame-level resampling would overstate effective sample size.'),
        q('Among predictions assigned probability near 0.8, the event occurs only 55% of the time on a representative holdout. What is the primary issue?',
          ['The classifier must have poor ranking everywhere', 'The labels must be balanced before calibration can be assessed', 'The decision threshold is necessarily too high', 'The model is overconfident and poorly calibrated in that score region'], 3,
          'Calibration compares predicted probabilities with empirical frequencies. This region is overconfident; discrimination and the best operating threshold are separate questions.'),
        q('An A/B test estimates a +0.4% conversion lift with a 95% confidence interval from −0.2% to +1.0%. What is the sound conclusion?',
          ['The treatment is proven harmful because the interval includes a negative value', 'The data remain compatible with a small loss or a useful gain, so the decision should reflect uncertainty and practical costs', 'The treatment is proven beneficial because the point estimate is positive', 'Exactly 95% of users experienced a lift inside that interval'], 1,
          'Because the interval crosses zero, the estimate does not rule out either a small negative effect or a positive one at that confidence level. Product action should incorporate decision costs, power, and practical effect size.'),
      ]
    },
    {
      id: 'rapid-fire-readiness',
      area: 'foundations',
      kind: 'rapid-fire',
      title: 'No-notes readiness rapid fire',
      questions: [
        q('Validation improves while training accuracy decreases after adding augmentation. Is that automatically bad?',
          ['Yes, training and validation accuracy must move in the same direction', 'No, harder augmented examples can reduce training accuracy while improving generalization', 'Yes, augmentation should be applied only after the model converges', 'No, because any validation improvement proves the split is valid'], 1,
          'Augmentation changes training difficulty, so lower training accuracy can accompany better valid-split generalization. The result is not automatically good either: split validity and slice behavior still need verification.'),
        q('What is the first thing to verify when production quality drops immediately after a deployment?',
          ['Retrain a higher-capacity model on the same data', 'Versioned code/model/threshold/preprocessing differences and input health', 'Increase regularization to improve generalization', 'Wait for a large labeled sample before checking serving changes'], 1,
          'An abrupt deployment-aligned change first implicates version, serving, preprocessing, threshold, traffic routing, or input-contract issues. Retraining and delayed labels come after checking the correlated operational change.'),
        q('Under the classical covariate-shift assumption, what changes?',
          ['P(Y|X) changes while P(X) is fixed', 'P(X) changes while P(Y|X) is assumed stable', 'P(Y) changes while P(X|Y) is assumed stable', 'Only the model prediction distribution changes'], 1,
          'Classical covariate shift changes the input distribution P(X) while assuming the conditional P(Y|X) remains stable. A conditional change is concept drift; a changed class prior under stable P(X|Y) is label shift; prediction shift alone does not identify the cause.'),
        q('Why does AdamW decouple weight decay?',
          ['An L2 gradient penalty and direct decay are identical under every optimizer', 'Adaptive gradient scaling makes an L2 penalty differ from direct parameter shrinkage', 'Decoupling removes the need for first- and second-moment estimates', 'Decoupling automatically chooses which parameter groups should decay'], 1,
          'Adam scales gradient coordinates adaptively, so adding λθ to the gradient is not the same as direct shrinkage. AdamW separates the decay update; moment estimation and explicit parameter-group choices still remain.'),
        q('Which monitoring signal is the strongest evidence of concept drift?',
          ['The input feature mean changed', 'Prediction entropy changed', 'Labeled conditional performance changed under comparable evaluation', 'An embedding-distance alarm fired on unlabeled traffic'], 2,
          'Concept drift concerns P(Y|X). Input, embedding, or prediction shifts are useful alarms but do not identify that conditional change; comparable labeled outcomes provide the strongest evidence among these choices.'),
        q('Why can nearest-neighbor retrieval require a full index rebuild after encoder replacement?',
          ['Matching embedding dimensions guarantees old and new vectors remain comparable', 'Old and new embeddings may occupy incompatible vector spaces', 'L2-normalizing both versions always aligns their coordinate systems', 'A dual-index migration changes only storage cost, not result semantics'], 1,
          'Vectors from different representation versions are generally not comparable even when dimension and normalization match. Re-embedding the catalog—or deliberately running version-compatible dual indexes—is needed to preserve query/index semantics.'),
        q('What is a strong baseline for a new CV problem with limited data?',
          ['Train the largest available architecture from random initialization', 'A simple pretrained model with a clear metric and valid split', 'Select the newest architecture by repeatedly tuning on the test set', 'Freeze a pretrained backbone permanently without comparing fine-tuning'], 1,
          'A simple pretrained baseline quickly tests data, labels, metric, and transfer. Scratch training, test-set selection, and an unvalidated always-frozen policy confound the comparison.'),
        q('What does a canary deployment add beyond shadowing?',
          ['Offline replay of historical requests', 'Real user decisions and impact on a controlled fraction', 'Mirrored live traffic whose outputs are never served', 'A full rollout protected only by the ability to roll back'], 1,
          'A canary serves a limited share of real decisions, exposing actual user and system impact while containing risk. Offline replay and non-serving mirrored traffic are not canaries, while a full rollout is not controlled exposure.'),
        q('Why should threshold and model version be tracked separately?',
          ['Embedding the threshold in a model filename fully identifies every serving decision', 'Operational behavior can change without retraining when the threshold changes', 'Threshold versioning matters only when the encoder architecture changes', 'Logged score histograms are enough to reconstruct the exact threshold later'], 1,
          'A threshold is independent production configuration that can change precision, recall, load, and risk without new weights. Filenames or score histograms do not substitute for recording the exact deployed value and rollout.'),
        q('When is a random validation split especially dangerous?',
          ['Independent tabular rows sampled from the deployment distribution', 'Temporal prediction or grouped entities with correlated samples', 'A small independent dataset that uses stratification', 'Independent images with no shared subject, site, or acquisition session'], 1,
          'Random splitting leaks future or group-specific information when deployment requires generalization across time or entities. Small size may increase uncertainty, but without dependence it does not create this particular leakage.'),
        q('An offline detector gains 1.5 mAP but doubles p99 latency on the target device. What is the senior next step?',
          ['Ship because offline accuracy is the primary objective', 'Reject it immediately without profiling', 'Evaluate end-to-end utility against latency, throughput, and slice guardrails, then choose the operating tradeoff', 'Compare parameter count only'], 2,
          'Model selection is a constrained system decision. Profile the real pipeline and determine whether the quality gain improves product utility within latency, throughput, reliability, and slice requirements.'),
        q('A calibrated classifier is moved to a region with a different class prevalence. Which assumption is safest?',
          ['Its calibration is guaranteed to transfer because ranking is unchanged', 'Calibration may change and must be re-evaluated on representative target data', 'Only the model weights can affect calibration', 'The decision threshold should remain fixed whenever ROC-AUC is stable'], 1,
          'Calibration depends on the deployment distribution, including prevalence. Stable ranking does not guarantee stable probabilities or an unchanged cost-optimal threshold.'),
        q('A feature is computed from a customer’s full 30-day history, but the prediction is supposed to occur on day 10. What is the core risk?',
          ['Label or temporal leakage from information unavailable at prediction time', 'Underfitting caused by too few future features', 'Calibration error caused only by class imbalance', 'Excess variance caused by using a deterministic feature'], 0,
          'The offline feature includes future information that serving cannot know on day 10. Point-in-time-correct feature generation and replay are required for a valid estimate.'),
        q('Labels arrive six weeks after predictions. Which monitoring plan is most defensible?',
          ['Wait six weeks and monitor nothing meanwhile', 'Use input, data-quality, score, and system-health leading indicators, then backfill delayed labeled performance', 'Treat prediction entropy as proof of accuracy', 'Retrain automatically whenever feature means move'], 1,
          'Leading indicators can detect pipeline and distribution anomalies quickly, but they do not replace outcome measurement. Join delayed labels later and evaluate performance, calibration, and slices by model version.'),
        q('An active-learning loop selects only the model’s lowest-confidence images. What failure should you anticipate?',
          ['The labeled set may overrepresent ambiguous cases and miss confident systematic errors', 'The selected labels become statistically independent', 'The model is guaranteed to become calibrated', 'Low confidence always identifies the highest business value'], 0,
          'Uncertainty sampling changes the labeled distribution and can overlook confident blind spots. Mix strategies, preserve an unbiased evaluation set, and monitor coverage and selection propensity.'),
        q('Per-device batch size drops from 32 to 2 during distributed CV training, and BatchNorm becomes unstable. What is the most defensible response?',
          ['Increase dropout because BatchNorm statistics do not depend on batch size', 'Verify train/eval behavior, then benchmark synchronized BatchNorm, GroupNorm, or frozen pretrained statistics', 'Estimate BatchNorm statistics from the validation set during every epoch', 'Remove normalization from every layer without an ablation'], 1,
          'Tiny local batches make BatchNorm estimates noisy. First rule out mode and running-statistic bugs, then compare synchronization, batch-size-independent normalization, or carefully frozen pretrained statistics on the real task.'),
        q('A model improves the global metric but regresses sharply for one safety-critical camera type. What should govern release?',
          ['The global average because it has more samples', 'Predeclared critical-slice guardrails alongside the aggregate objective', 'Training loss because it is less noisy', 'The best-performing camera type'], 1,
          'Aggregate gains can conceal unacceptable localized harm. Release criteria should include representative critical slices, uncertainty, and an explicit risk owner.'),
        q('A new encoder changes embedding dimension from 512 to 768. What must a safe rollout include?',
          ['Writing 768-dimensional queries into the old 512-dimensional index', 'A versioned embedding contract and compatible index migration or dual-read path', 'Only renaming the model artifact', 'Reusing cached vectors without version metadata'], 1,
          'Embedding dimension and geometry are interface contracts. Version vectors and indexes, prevent incompatible mixing, validate a dual path where needed, and define rollback.'),
        q('Both training and validation performance are poor. Should stronger dropout or weight decay be the first response?',
          ['Yes, stronger regularization always improves validation performance', 'Yes, a small train/validation gap proves the model has high variance', 'No; first verify data, objective, optimization, and capacity because more regularization can worsen high bias', 'No; remove the validation split and tune on all available data'], 2,
          'Poor training fit is evidence against a pure variance diagnosis. Validate the pipeline and optimization, then address capacity or objective mismatch before adding regularization that may further suppress fitting.'),
        q('A model abstains on uncertain cases and sends them to human review. Which evaluation is complete?',
          ['Accuracy only on non-abstained cases', 'Coverage, selective risk, reviewer capacity, turnaround, and end-to-end errors including reviewed cases', 'The abstention rate alone', 'ROC-AUC before introducing abstention'], 1,
          'Selective prediction trades automated coverage for lower risk and human load. Evaluate the full workflow, including capacity, delays, reviewer quality, and errors across both automated and reviewed paths.'),
      ]
    },
    {
      id: 'modern-cv-judgment',
      area: 'modern-cv',
      kind: 'modern-cv',
      title: 'Modern CV model-selection check',
      questions: [
        q('You need cross-modal text-to-image retrieval across a broad catalog. Best starting representation?',
          ['A supervised image classifier’s final class logits', 'CLIP-style dual image/text encoders in a shared embedding space', 'A self-supervised image encoder with no text objective', 'An object detector’s box-regression features without language training'], 1,
          'CLIP-style dual encoders explicitly align image and text embeddings in a shared space, making them a strong retrieval baseline. Image-only supervision may produce useful visual features but does not provide the required cross-modal alignment.'),
        q('You need reusable visual features for dense tasks but text alignment is not important. Best starting point?',
          ['DINOv2-style self-supervised features', 'CLIP text embeddings used without an image encoder', 'A classifier’s final class probabilities as the dense feature map', 'Raw RGB patches compared directly with cosine similarity'], 0,
          'DINOv2 targets reusable visual representations and often transfers to dense perception with task heads. Text-only, class-probability, and raw-pixel representations do not provide comparable spatial visual features.'),
        q('What is the main computational risk of reducing ViT patch size at fixed resolution?',
          ['Token count falls because each patch has fewer pixels', 'More tokens and much higher attention cost', 'Attention cost stays linear because embedding width is unchanged', 'Only the patch projection cost changes; transformer-block cost is fixed'], 1,
          'Smaller patches increase token count. Full self-attention grows quadratically in token count, so fixed embedding width does not make transformer-block cost linear or constant.'),
        q('What does canonical DETR replace with set prediction and matching?',
          ['All image preprocessing', 'Anchor design and standard NMS in the core detector', 'The classification loss', 'The image backbone'], 1,
          'Object queries and bipartite matching produce a set of distinct predictions, removing anchors and canonical NMS.'),
        q('What is a sensible production role for SAM2 in a domain with limited labels?',
          ['Use its masks as ground truth without a domain audit', 'Annotation acceleration and an evaluated promptable component', 'Replace a validated domain model because prompts eliminate distribution shift', 'Feed its masks downstream without measuring propagated errors'], 1,
          'SAM2 can accelerate annotation and support interactive segmentation, but domain performance and workflow safety require evaluation. Promptability does not remove distribution shift, label review, or downstream error analysis.'),
        q('Grounding DINO plus SAM composes which two capabilities?',
          ['Text-conditioned boxes followed by promptable masks', 'Promptable masks followed by text-conditioned box training', 'Closed-set class logits followed by mask upsampling', 'Class-agnostic boxes followed by an ungrounded captioner'], 0,
          'Grounding DINO maps phrases to boxes, and those boxes can prompt SAM to produce masks. The composition is open-vocabulary grounding followed by promptable segmentation, not closed-set classification or caption generation.'),
        q('Why can a VLM be dangerous for structured document extraction?',
          ['Schema-valid output guarantees every field is visually supported', 'Fluent output can invent unsupported fields unless grounded and validated', 'Removing OCR always improves evidence fidelity', 'Low decoding temperature guarantees factual extraction'], 1,
          'Generative fluency can hide unsupported fields. Schema validity, OCR-free generation, or low temperature does not prove visual grounding; use evidence links, validation, abstention, and field-level evaluation.'),
        q('When might a compact CNN beat a transformer in production?',
          ['Whenever the transformer has a higher pretraining benchmark, regardless of hardware', 'Tight edge latency, small data, mature optimized kernels, and local patterns', 'Whenever input resolution is fixed, regardless of target runtime', 'Whenever the training set is small, even if a strong transformer checkpoint transfers better'], 1,
          'Architecture choice includes data, transfer quality, and target hardware. CNN inductive bias and optimized kernels can dominate under the stated constraints, but neither fixed resolution nor dataset size alone decides the result.'),
        q('What must be measured after INT8 quantization?',
          ['Calibration-set accuracy before conversion only', 'End-to-end target-hardware latency plus overall and slice accuracy', 'Kernel microbenchmark speed without preprocessing or transfer overhead', 'Aggregate accuracy without latency or slice checks'], 1,
          'Quantization value depends on actual target-runtime support and acceptable end-to-end quality. Calibration data, kernel speed, or aggregate accuracy alone can miss conversion, overhead, fallback, and slice regressions.'),
        q('Synthetic diffusion data improves training accuracy. What validates its usefulness?',
          ['A blinded realism rating of generated samples alone', 'Improvement on a real, untouched, deployment-representative holdout without slice regressions', 'A monotonic gain as more synthetic samples are added', 'Lower diffusion-model loss on its own training distribution'], 1,
          'Only untouched real-data evaluation demonstrates useful transfer. Realism ratings, synthetic volume, and generator loss do not rule out artifacts, leakage, label errors, or deployment-slice regressions.')
      ]
    }
  ];

  window.InterviewPrepData = {
    ...(window.InterviewPrepData || {}),
    quizzes
  };
})();
